//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministrasiTombol
    {
        public string Kode { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public string Class { get; set; }
        public string KodeMenu { get; set; }
        public string Parameter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
