//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministrasiUser
    {
        public string Kode { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public string Telepon { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> IsAdministrator { get; set; }
        public bool Aktif { get; set; }
        public string KodePlant { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Password { get; set; }
    }
}
