//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NilaiScoring
    {
        public int Kode { get; set; }
        public string KodeKaryawan { get; set; }
        public string KodeLowongan { get; set; }
        public Nullable<int> KodeKriteria { get; set; }
        public Nullable<double> NilaiGap { get; set; }
        public Nullable<double> NilaiBobot { get; set; }
        public Nullable<double> NilaiAlternatif { get; set; }
        public Nullable<double> RangkingScoring { get; set; }
        public Nullable<double> NilaiTotal { get; set; }
        public Nullable<double> Ncf { get; set; }
        public Nullable<double> Nsf { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
