//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwRankingPosisi
    {
        public string Periode { get; set; }
        public Nullable<int> Jumlah { get; set; }
        public string Pendidikan { get; set; }
        public string Posisi { get; set; }
        public string Kode { get; set; }
        public string Nama { get; set; }
        public Nullable<double> NilaiTotal { get; set; }
    }
}
